baseURL: https://yanuhyaportfolio.netlify.app
languageCode: en-us
title: Anuhya
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Dive in
    subtitle: |-
      Welcome to my website! Dive in to learn about me and my work
    title: Hi, my name is Anuhya
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        #street: Street
        #title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: yanuhya@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/AnuhyaYallaban1
      - icon: fa-facebook
        label: Facebook
        url: https://m.facebook.com/anuhya.y
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/anuhya_y/
      - icon: fa-github
        label: GitHub
        url: https://github.com/yanuhya
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/yanuhya/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: IMG_Anuhya.jpg
        subtitle: glimpse(me)
        title: About me
        url: blogs/anuhya
      - image: pic02.jpg
        subtitle: Life expectency over years
        title: gapminder
        url: blogs/gapminder
      - image: pic03.jpg
        subtitle: Analysing pay scale data by gender
        title: Omega Group Pay Discrimination
        url: blogs/payDiscrimination
      - image: pic04.jpg
        subtitle: How GDP has changed over time
        title: GDP
        url: blogs/gdp
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: YRBSS
        url: blogs/yrbss
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  #two:
  #  buttonText: Get Started
  #  enable: yes
  #  subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
  #    \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
  #    condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
  #    pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
  #    Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
  #    amet pharetra et feugiat tempus."
  #  title: Massa libero
  #  url: blogs
